name: COD
author: CentrumGuy
main: com.CentrumGuy.CodWarfare.Main
version: 2.7

commands:
   cod:
     description: The basic command for all Call of Duty commands
     usage: /<command>
   callofduty:
     description: The basic command for all Call of Duty commands
     usage: /<command>
   codwar:
     description: The basic command for all Call of Duty commands
     usage: /<command>
   codwarfare:
     description: The basic command for all Call of Duty commands
     usage: /<command>
   warfare:
     description: The basic command for all Call of Duty commands
     usage: /<command>
   callofdutywarfare:
     description: The basic command for all Call of Duty commands
     usage: /<command>
   callofdutywar:
     description: The basic command for all Call of Duty commands
     usage: /<command>